theme: jekyll-theme-slate
title: Col·lectiu Nightingale
description: Sóm un grup de professionals de les dades (científics de dades, enginyers, personal acadèmic i de recerca) preocupats per la crisis desencadenada per la pandèmia de COVID-19. 
project_title: Col·lectiu Nightingale
project_tagline: Carta oberta a les administracions públiques Catalanes i Espanyoles
